version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - 7z a ../deployment_package.zip .
      - cd ..
      - 7z a deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Uploading to S3...."
      - aws s3 cp deployment_package.zip s3://lambda-builds-zip27/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name github-to-lambda-cicd --s3-bucket lambda-builds-zip27 --s3-key deployment_package.zip
      - echo "Deployment complete!"